"""Treatment evidence stays inside a stated physical-product clause."""

import pytest

from tools.product_type_reader.treatment_rules import _normalize, extract_treatments


def read(description: str, noun: str, evidence: str | None = None) -> tuple[str, ...]:
    title = _normalize(description.split("_")[0])
    start = title.index(noun)
    return extract_treatments(
        description,
        normalized_title=title,
        product_span=(start, start + len(noun)),
        physical_evidence=evidence if evidence is not None else noun,
    )


@pytest.mark.parametrize(
    "description,noun,evidence,expected",
    [
        ("Foil canvas", "canvas", "foil canvas", ("Foil",)),
        ("Static LED canvas", "canvas", "static led canvas", ("LED",)),
        ("Winter LED wire art on MDF box", "mdf box", "mdf box", ("LED",)),
        ("LED-lit forest silhouette MDF box art", "mdf box art", "mdf box art", ("LED",)),
        ("MDF metallic print", "print", "metallic print", ("Metallic",)),
        ("High gloss canvas", "canvas", "high gloss canvas", ("High Gloss",)),
        ("High Gloss Zorblax Pals Canvas", "canvas", "canvas", ("High Gloss",)),
        ("HG CRYSTL GRVL CNVS", "canvas", "canvas", ("Crystal Gravel", "High Gloss")),
        ("Canvas with moving LED", "canvas", "canvas moving led", ("LED",)),
        ("Canvas with copper foil", "canvas", "canvas", ("Foil",)),
        ("Canvas with metallic leaf", "canvas", "canvas", ("Metallic Leaf",)),
        ("Silver metallic leaf on glass", "glass", "glass", ("Silver Leaf",)),
        ("Gold metallic leaf on glass", "glass", "glass", ("Gold Leaf",)),
        ("Canvas with spot varnish", "canvas", "canvas", ("Spot Varnish",)),
        ("MDF plaque with wood veneer", "plaque", "mdf plaque", ("Veneer",)),
        ("Framed MDF print with invisible ink and UV light", "print", "mdf print", ("Invisible Ink", "UV Light")),
        ("Canvas with sequins", "canvas", "canvas", ("Sequins",)),
        ("Ceramic tray with gloss", "tray", "ceramic tray", ("Gloss",)),
        ("Painted glass panel", "glass", "painted glass", ("Painted",)),
        ("Printed Canvas Multipack set of 4 w/Spot Varnish", "canvas", "canvas", ("Spot Varnish",)),
        ("Printed Canvas w Sport Varnish", "canvas", "canvas", ("Spot Varnish",)),
        ("Canvas with spot gloss", "canvas", "canvas", ("Spot Gloss",)),
        ("Embossed print", "print", "embossed print", ("Embossed",)),
        ("Screenprinted canvas", "canvas", "screenprinted canvas", ("Screenprint",)),
        ("Distressed finish canvas", "canvas", "distressed finish canvas", ("Distressed",)),
        ("Canvas with applique", "canvas", "canvas applique", ("Applique",)),
        ("Glass art with crystal gravel", "art", "glass art", ("Crystal Gravel",)),
        ("Canvas with button embellishment", "canvas", "canvas", ("Button Embellishment",)),
        ("Canvas with glue embellishment", "canvas", "canvas", ("Glue Embellishment",)),
        ("Canvas with glitter and foil", "canvas", "canvas glitter and foil", ("Foil", "Glitter")),
        ("Canvas w diamond dust glitter", "canvas", "canvas", ("Diamond Dust", "Glitter")),
        ("MDF box with copper foil artwork panel", "box", "mdf box", ()),
        ("MDF box with copper foil decorative panel", "box", "mdf box", ("Foil",)),
        ("Storage chest and gold foil", "chest", "storage chest", ("Foil",)),
        ("Canvas with silver glitter finish", "canvas", "canvas", ("Glitter",)),
        ("LED franchise canvas", "canvas", "canvas", ("LED",)),
        ("Canvas with moving LEDs", "canvas", "canvas", ("LED",)),
        ("Canvas with goldfoil", "canvas", "canvas", ("Foil",)),
        ("Canvas with foil15x14", "canvas", "canvas", ("Foil",)),
        ("Canvas with gltr", "canvas", "canvas", ("Glitter",)),
        ("Canvas with glitter 16x20 artwork garden", "canvas", "canvas glitter", ("Glitter",)),
        ("11x14 high gloss canvas artwork garden", "canvas", "high gloss canvas", ("High Gloss",)),
        ("Canvas 16x20_foil", "canvas", "canvas", ("Foil",)),
        ("Canvas w dripping metallic paint 20x20", "canvas", "canvas", ("Metallic",)),
        ("Canvas w metallic finish", "canvas", "canvas", ("Metallic",)),
        ("Printed canvas w fabric bow", "canvas", "canvas", ("Attachment",)),
        ("Metal plate emb canvas", "canvas", "canvas", ("Attachment",)),
        ("Wire emb canvas", "canvas", "canvas", ("Attachment",)),
        ("Canvas with metal logo", "canvas", "canvas", ("Attachment",)),
        ("MTLC CNVS", "canvas", "canvas", ("Metallic",)),
        ("MTLLIC Canvas", "canvas", "canvas", ("Metallic",)),
        ("MTLLC CNVS", "canvas", "canvas", ("Metallic",)),
        ("Printed Canvas w DRPPNG MTLLIC Paint", "canvas", "canvas", ("Metallic",)),
        ("Metallic Print on MDF Box", "box", "box", ("Metallic",)),
        ("Canvas with clear gel", "canvas", "canvas", ("Gel Coat",)),
        ("Canvas with gel blue sunrise", "canvas", "canvas", ("Gel Coat",)),
        ("Glass shadowbox w gel_Daybreak", "shadowbox", "shadowbox", ("Gel Coat",)),
        ("Gel canvas", "canvas", "gel canvas", ("Gel Coat",)),
        ("Flexible gel sticker with glitter", "sticker", "gel sticker glitter", ("Glitter",)),
        ("Glow in dark canvas", "canvas", "glow in dark canvas", ("Glow in the Dark",)),
        ("Flexible gel sticker with silkscreen printing", "sticker", "gel sticker", ("Screenprint",)),
        ("Printed canvas w gel handpaint", "canvas", "canvas", ("Gel Coat", "Handpaint")),
        ("Boxed MDF w decoupaged paper print", "mdf", "boxed mdf", ("Decoupage",)),
        ("Boxed MDF w decoupaged paper print", "print", "paper print", ("Decoupage",)),
        ("Ceramic cube with decal", "cube", "ceramic cube", ("Decal",)),
        ("Framed MDF print scratch-off puzzle poster", "print", "mdf print", ("Scratch-Off",)),
        ("Floater frame canvas w flower and beading", "canvas", "canvas", ("Beading",)),
        ("Floater frame canvas w 3D flower & beading", "canvas", "canvas", ("Beading",)),
        ("Greyboard storage chest w spot gloss", "chest", "chest", ("Spot Gloss",)),
        ("Canvas with chenile patch", "canvas", "canvas", ("Chenille Patch",)),
        ("Button Art", "art", "button art", ("Button Embellishment",)),
        ("HG CNVS", "canvas", "canvas", ("High Gloss",)),
        ("HGH GLSS Canvas", "canvas", "canvas", ("High Gloss",)),
        ("Canvas w gold embelishment", "canvas", "canvas", ("Embellished",)),
        ("Canvas with chiffon applique and embroidery", "canvas", "canvas", ("Applique", "Embroidery")),
        ("Ceramic block_Copper foil_4x4", "block", "ceramic block", ("Foil",)),
        ("Ceramic block_Spring petals and Foil_Peach_7x7", "block", "ceramic block", ("Foil",)),
        ("Ceramic block_Letters in Foil_Beige_7x7", "block", "ceramic block", ("Foil",)),
        ("Storage bin_Geometric Pattern Gold Foil_7x7", "bin", "storage bin", ("Foil",)),
        ("Canvas in frame_Pink shapes with glitter and foil_7x7", "canvas", "canvas", ("Foil", "Glitter")),
        ("Sample set embellished 9x13 canvas two-pack", "canvas", "canvas", ("Embellished",)),
        ("9x13 handpainted meadow canvas", "canvas", "canvas", ("Handpaint",)),
        ("Canvas Blue Finch Hand Painted 21x29", "canvas", "canvas", ("Handpaint",)),
        ("Canvas with glue coat texture", "canvas", "canvas", ("Glue Embellishment",)),
        ("Float Frme w highgloss Blck n whte wman leaves", "frme", "frme", ("High Gloss",)),
        ("Canvas w Sherpa Fabric", "canvas", "canvas", ("Attachment",)),
        ("Canvas w Faux Fur", "canvas", "canvas", ("Attachment",)),
        ("Canvas with bows", "canvas", "canvas", ("Attachment",)),
        ("Canvas with bows and glitter", "canvas", "canvas", ("Attachment", "Glitter")),
        ("12x16 Canvas with bows Luna Star Dream Believe Achieve", "canvas", "canvas", ("Attachment",)),
        ("Floater Framed Canvas w Hgh Glass", "canvas", "canvas", ("High Gloss",)),
        ("MDF box frame with glitterStorybook Hero", "box", "box", ("Glitter",)),
        ("MDF Photo Frame_Pink Glitter Insert_4x6", "frame", "frame", ("Glitter",)),
        ("Canvas with genuine glitter", "canvas", "canvas", ("Glitter",)),
        ("Canvas with gold foil finish", "canvas", "canvas", ("Foil",)),
        ("Canvas with gold leafs and pearls", "canvas", "canvas", ("Gold Leaf", "Pearls")),
        ("Canvas with gold leafs and pearls Storybook", "canvas", "canvas", ("Gold Leaf", "Pearls")),
        ("Canvas with metallic puffpaint", "canvas", "canvas", ("Metallic", "Puff Paint")),
        ("Canvas with metallic puffpaint Storybook", "canvas", "canvas", ("Metallic", "Puff Paint")),
        ("Canvas w high gloss and clear gravel", "canvas", "canvas", ("Gravel", "High Gloss")),
        ("Canvas w gold leaf and heavy handpaint", "canvas", "canvas", ("Gold Leaf", "Handpaint")),
        ("HNDPNT CNVS", "canvas", "canvas", ("Handpaint",)),
        ("Paint-effect canvas", "canvas", "canvas", ("Paint Effect",)),
        ("Canvas with rhinestonel embellishment", "canvas", "canvas", ("Rhinestone",)),
        ("MDF box engraved forest motif", "box", "mdf box", ("Engraved",)),
        ("Printed glass with pressed leaves", "glass", "glass", ("Pressed Leaves",)),
        ("Framed art w beaded garland", "art", "art", ("Beaded Garland",)),
        ("Shadowbox w diamnd dust", "shadowbox", "shadowbox", ("Diamond Dust",)),
        ("Canvas set of 4 w faux leather patch", "canvas", "canvas", ("Faux Leather Patch",)),
        ("Canvas wih gel coat", "canvas", "canvas", ("Gel Coat",)),
        ("Functional hook_LED and MDF_8x9", "hook", "hook", ("LED",)),
        ("Galvanized steel box with PVC applique", "box", "box", ("Applique", "Galvanized")),
        ("Various asst licenses and Blue Orchard canvas w foil, glitter, and gel coat 19x25", "canvas", "canvas", ("Foil", "Gel Coat", "Glitter")),
        ("Floated canvas w mat & gold leaf_Green orchard_19x25", "canvas", "canvas", ("Gold Leaf",)),
        ("Wall hook_Stained Wood_19x25", "hook", "hook", ("Stained",)),
        ("Printed canvas S/2 Glitter Embellishment_Quiet meadow_19x25", "canvas", "canvas", ("Glitter",)),
        ("Embssd Pper Prnt 18x22", "print", "print", ("Embossed",)),
        ("Glass shadowbox w foil and textured linen print 18x22", "shadowbox", "shadowbox", ("Foil", "Textured")),
        ("Stretched PU w screen print 18x22", "print", "print", ("Screenprint",)),
        ("Pinboard w faux grass_Field sport_18x22", "pinboard", "pinboard", ("Faux Grass",)),
        ("Wrapped linen in floating frame one word embroidery_Gratitude_18x22", "frame", "frame", ("Embroidery",)),
        ("Canvas highgloss landscape scene 18x22", "canvas", "canvas", ("High Gloss",)),
        ("Glitter UV Lacquer Art", "art", "art", ("Glitter", "UV Lacquer")),
        ("Printed glass w dust floral study 18x22", "glass", "glass", ("Dust",)),
        ("Printed glass w diamond dust floral study 18x22", "glass", "glass", ("Diamond Dust",)),
        ("MDF plque w hlfoil pper 18x22", "plaque", "mdf plaque", ("Foil",)),
        ("Canvas with hanpainted glitter", "canvas", "canvas", ("Glitter", "Handpaint")),
        ("Floater Frame Faux Leather w Screenprint", "frame", "frame", ("Screenprint",)),
        ("Mini Stained Glass with Bow Frame and Chain", "stained glass", "stained glass", ("Stained Glass",)),
        ("Distressed Canvas_American Flag", "canvas", "canvas", ("Distressed",)),
        ("Distressed canvas", "canvas", "distressed canvas", ("Distressed",)),
        ("Fictional Hero DISTRESSEDCANVAS", "canvas", "canvas", ("Distressed",)),
        ("Pressed Leaves under Glass in Distressed Wooden Frame", "frame", "frame", ("Distressed",)),
        ("Sample MDF Textured Frame Otter in camp", "frame", "mdf textured frame", ("Textured",)),
        ("Printed Glass with Textured Background_Winter Shop", "glass", "glass", ("Textured",)),
        ("MDF Block w Beaded Accent_USA colors", "block", "block", ("Beaded",)),
        ("Printed Canvas w Plaster Word_Eat Sleep Game Repeat", "canvas", "canvas", ("Plaster Word",)),
        ("Framed Printed Glass with Dried Flowers_Be Grateful", "glass", "glass", ("Dried Flowers",)),
        ("Floater Frame Canvas w Gold Leaf and Puffy Paint_Dark castle", "canvas", "canvas", ("Gold Leaf", "Puff Paint")),
        ("Canvas in Floating Frame multiple embellishment_Abstract art", "canvas in floating frame", "canvas in floating frame", ("Embellished",)),
        ("Floating character MDF box with metallic foil Hulk", "box", "box", ("Foil",)),
    ],
)
def test_stated_physical_treatment(description, noun, evidence, expected):
    assert read(description, noun, evidence) == expected


@pytest.mark.parametrize(
    "description,noun,evidence",
    [
        ("Canvas gold foil artwork", "canvas", "canvas"),
        ("Canvas_foil hero artwork", "canvas", "canvas"),
        ("Canvas_Stained Wood artwork_19x25", "canvas", "canvas"),
        ("Printed canvas artwork S/2 Glitter Embellishment", "canvas", "canvas"),
        ("Glass shadowbox artwork with textured linen print 18x22", "shadowbox", "shadowbox"),
        ("Canvas artwork of a faux grass pinboard", "canvas", "canvas"),
        ("Canvas one word embroidery artwork 18x22", "canvas", "canvas"),
        ("Wall art with UV lacquer artwork", "art", "wall art"),
        ("Printed glass dust artwork 18x22", "glass", "glass"),
        ("Printed glass with simulated dust 18x22", "glass", "glass"),
        ("MDF plque, MDF plque w holofoil 18x22", "plaque", "plaque"),
        ("Ceramic block_Foil hero artwork_7x7", "block", "ceramic block"),
        ("Printed canvas_Gold foil effect_7x7", "canvas", "canvas"),
        ("Wall clock_Butterfly motif w Gold Foil_12in", "clock", "wall clock"),
        ("Canvas_Winter foil scene", "canvas", "canvas"),
        ("Canvas_Artwork with LED", "canvas", "canvas"),
        ("Canvas 16x20 foil artwork", "canvas", "canvas"),
        ("Canvas without foil", "canvas", "canvas without foil"),
        ("Canvas no glitter", "canvas", "canvas no glitter"),
        ("Metal bow frame", "frame", "metal bow frame"),
        ("Canvas with foil artwork", "canvas", "canvas"),
        ("Canvas fairy hero portrait foil", "canvas", "canvas foil"),
        ("Canvas fairy hero portrait glitter", "canvas", "canvas glitter"),
        ("Textured canvas", "canvas", "textured canvas"),
        ("Canvas with lights", "canvas", "canvas"),
        ("Lightup silhouette", "silhouette", "lightup silhouette"),
        ("Canvas 16x20 artwork girl with glitter", "canvas", "canvas glitter"),
        ("Canvas 16x20 girl with glitter", "canvas", "canvas glitter"),
        ("Canvas 16in x20in girl with glitter", "canvas", "canvas glitter"),
        ("Canvas 30cm x40cm artwork with foil", "canvas", "canvas foil"),
        ("Canvas 12 inch artwork with glitter", "canvas", "canvas glitter"),
        ("Canvas artwork girl with foil", "canvas", "canvas foil"),
        ("Canvas graphic stars with LEDs", "canvas", "canvas led"),
        ("Canvas with foil artwork hero", "canvas", "canvas foil"),
        ("Canvas with bow iconic repeat graphic", "canvas", "canvas"),
        ("Canvas 16x20 artwork with metallic", "canvas", "canvas"),
        ("Canvas 16x20 artwork with spot gloss", "canvas", "canvas"),
        ("Canvas 16x20 graphic button art", "canvas", "canvas"),
        ("Assorted sketches 9x13 Canvas w and w/o embellishments", "canvas", "canvas embellished"),
        ("Canvas with and without glitter", "canvas", "canvas glitter"),
        ("DIY embroidery kit with hoop and needles", "kit", "embroidery kit"),
        ("Fabric bow wall art with hearts and bows", "wall art", "wall art"),
        ("Canvas with bows in printed graphic", "canvas", "canvas"),
        ("Canvas with bow frame", "canvas", "canvas"),
        ("PE Rattan Wall Shelf with Bow Princess Icons", "wall shelf", "wall shelf"),
        ("Canvas with bows, Canvas plain", "canvas", "canvas"),
        ("Prntd glss w glitter, prntd glss plain", "printed glass", "printed glass"),
        ("Frmd art undr glss, frmd art undr glss w foil", "framed art under glass", "framed art under glass"),
        ("MDF plaque and MDF holofoil plaque", "mdf plaque", "mdf plaque and mdf holofoil"),
        ("Canvas with fake glitter", "canvas", "canvas fake glitter"),
        ("Canvas with simulated gold foil", "canvas", "canvas simulated gold foil"),
        ("Canvas with foil effect", "canvas", "canvas foil effect"),
        ("Canvas paint effect graphic", "canvas", "canvas paint effect"),
        ("Canvas artwork with spot varnish", "canvas", "canvas spot varnish"),
        ("Canvas graphic with sequins", "canvas", "canvas sequins"),
        ("Printed glass graphic with pressed leaves", "glass", "glass"),
        ("Canvas with faux leather and cord", "canvas", "canvas"),
        ("Stained glass printed glass shadowbox", "printed glass", "printed glass"),
        ("LED graphic on MDF box", "box", "mdf box"),
        ("High Gloss Mystery Frame", "frame", "frame"),
        ("Canvas graphic with a decal design", "canvas", "canvas decal"),
        ("Flexible gel sticker", "sticker", "gel sticker"),
        ("Canvas with faux metallic foil", "canvas", "canvas faux metallic foil"),
        ("Canvas with fake silver foil", "canvas", "canvas fake silver foil"),
        ("Canvas without glitter and foil", "canvas", "canvas glitter and foil"),
        ("Canvas without foil and glitter", "canvas", "canvas foil and glitter"),
        ("Canvas artwork of hand painted forest", "canvas", "canvas"),
        ("MDF print round emblem with distressing", "print", "print"),
        ("MDF print grunge distressed texture", "print", "print"),
        ("Disny, SS domed grybrd strge chst w foil, domed grybrd strge chst w spt gloss 18x13", "domed greyboard storage chest", "domed greyboard storage chest w foil"),
    ],
)
def test_artwork_size_and_negation_do_not_supply_treatment(description, noun, evidence):
    assert read(description, noun, evidence) == ()


def test_product_span_is_required_and_validated():
    with pytest.raises(ValueError, match="product_span"):
        extract_treatments("Canvas", normalized_title="canvas", product_span=(8, 13), physical_evidence="")


def test_empty_description_gives_no_treatment():
    assert extract_treatments(None, normalized_title="canvas", product_span=(0, 6), physical_evidence="") == ()


@pytest.mark.parametrize("description,expected", [
    ("Canvas with foil and Canvas with glitter", ()),
    ("Canvas with foil, Canvas without foil", ()),
    ("Canvas with foil and Canvas with foil", ("Foil",)),
    ("Canvas with LEDs, Canvas without LEDs", ()),
    ("Canvas with LEDs and Canvas with LEDs", ("LED",)),
    ("Printed glass with foil and printed glass without foil", ()),
    ("Brand A, Brand B cnvs, cnvs w foil 12x16", ()),
    ("16X20 assorted canvas plain and foil", ()),
    ("2pc multi-pck cnvs w glttr, w foil 22x14", ()),
    ("Mlti-pck cnvs w glttr, foil, gel 22x14", ()),
    ("Metallic and plain canvas", ()),
    ("Printed cnvs, mtllc cnvs 16x16", ()),
])
def test_same_form_variants_keep_only_common_finish(description, expected):
    noun = "printed glass" if description.lower().startswith("printed glass") else "canvas"
    assert read(description, noun, noun) == expected


@pytest.mark.parametrize("description,expected", [
    ("Orchard greyboard lift-off lid bx, greyboard lift-off lid box w foil 18x20", ()),
    ("Orchard greyboard lift-off lid bx w foil, greyboard lift-off lid box w foil 18x20", ("Foil",)),
])
def test_repeated_lift_off_box_variants_share_only_common_finish(description, expected):
    assert read(description, "greyboard lift off lid box", "greyboard lift off lid box") == expected


@pytest.mark.parametrize("description,expected", [
    ("Tall MDF sign, tall MDF sign w LEDs 18x20", ()),
    ("Tall MDF sign red, tall MDF sign blue w LEDs 18x20", ()),
    ("Tall MDF sign w LEDs, tall MDF sign w LEDs 18x20", ("LED",)),
    ("Tall MDF sign red w LEDs, tall MDF sign blue w LEDs 18x20", ("LED",)),
    ("Tall MDF sign, tall MDF sign LED artwork 18x20", ()),
])
def test_repeated_tall_sign_variants_share_only_physical_finish(description, expected):
    assert read(description, "tall mdf sign", "tall mdf sign") == expected
