import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {recoveryDependencyPaths,RECOVERY_DEPENDENCY_ROOTS} from './lib/claim-recovery-dependencies.mjs';
test('actual trusted closure includes transitive review, eligibility, target and authority modules',()=>{const paths=recoveryDependencyPaths(path=>fs.readFileSync(path,'utf8'));for(const p of ['scripts/lib/lanes/admission.mjs','scripts/lib/lanes/review-leases.mjs','scripts/lib/lanes/reviewer-roster.mjs','scripts/lib/lanes/review-assignment.mjs','scripts/lib/reviewer-capabilities.mjs','scripts/lib/lanes/review-replacement.mjs','scripts/lib/lanes/queue-routing.mjs','scripts/orchestrator-flow/admission.mjs','scripts/orchestrator-flow/outcome-lifecycle.mjs','scripts/lib/pr-content-equivalence.mjs','scripts/proofs/shared-db-2870-observation.mjs','scripts/lib/session-authority.mjs'])assert.ok(paths.includes(p),p)});
test('new static transitive dependency is protected automatically, including JSON and cycles',()=>{const files=Object.fromEntries(RECOVERY_DEPENDENCY_ROOTS.map(x=>[x,"import './new-critical.mjs';"]));for(const p of RECOVERY_DEPENDENCY_ROOTS)files[p]='';files[RECOVERY_DEPENDENCY_ROOTS[0]]="import './critical.mjs';";files['scripts/critical.mjs']="export {x} from './other.mjs'; import data from './roster.json' with {type:'json'};";files['scripts/other.mjs']="import './critical.mjs';";files['scripts/roster.json']='{}';const paths=recoveryDependencyPaths(p=>files[p]);assert.ok(paths.includes('scripts/other.mjs'));assert.ok(paths.includes('scripts/roster.json'));assert.equal(paths.filter(x=>x==='scripts/critical.mjs').length,1)});
test('missing dependency, path escape and excessive graph refuse',()=>{assert.throws(()=>recoveryDependencyPaths(()=>undefined),/unavailable/);assert.throws(()=>recoveryDependencyPaths(()=>"import '../../../outside.mjs';"),/path refused/);assert.throws(()=>recoveryDependencyPaths(()=>'',{maxFiles:1}),/exceeds bound/);assert.throws(()=>recoveryDependencyPaths(()=> 'large',{maxBytes:1}),/excessive/)});
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {execFileSync} from 'node:child_process';import {recoveryCodeUnchangedAt} from './lib/claim-recovery-dependencies.mjs';
test('actual Git main/local transitive review dependency changes refuse; unrelated file advances pass',()=>{
 const dir=mkdtempSync(join(tmpdir(),'claim-recovery-guard-'));const git=args=>execFileSync('git',['-C',dir,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});const put=(p,s)=>{mkdirSync(dirname(join(dir,p)),{recursive:true});writeFileSync(join(dir,p),s)};
 try{git(['init']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.invalid']);for(const p of RECOVERY_DEPENDENCY_ROOTS)put(p,'');put(RECOVERY_DEPENDENCY_ROOTS[0],"import './review-critical.mjs';");put('scripts/review-critical.mjs','export const permitted=false;');git(['add','.']);git(['commit','-m','reviewed tool']);const toolSha=git(['rev-parse','HEAD']).trim();assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha:toolSha,readOnlyGit:git}),true);put('unrelated.md','independent work');git(['add','unrelated.md']);git(['commit','-m','unrelated main advance']);const mainSha=git(['rev-parse','HEAD']).trim();assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha,readOnlyGit:git}),true);put('scripts/review-critical.mjs','export const permitted=true;');assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha,readOnlyGit:git}),false);git(['add','scripts/review-critical.mjs']);git(['commit','-m','critical main change']);assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha:git(['rev-parse','HEAD']).trim(),readOnlyGit:git}),false)}finally{rmSync(dir,{recursive:true,force:true})}
});
test('nonimported carry-forward policy registry byte changes refuse',()=>{
 const dir=mkdtempSync(join(tmpdir(),'claim-recovery-config-'));const git=args=>execFileSync('git',['-C',dir,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});const put=(p,s)=>{mkdirSync(dirname(join(dir,p)),{recursive:true});writeFileSync(join(dir,p),s)};const registry='config/review-carry-forward-stored-hashes-v1.json';
 try{git(['init']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.invalid']);for(const p of RECOVERY_DEPENDENCY_ROOTS)put(p,'');put(registry,'{"entries":[]}');git(['add','.']);git(['commit','-m','reviewed tool/config']);const toolSha=git(['rev-parse','HEAD']).trim();assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha:toolSha,readOnlyGit:git,extraPaths:[registry]}),true);put(registry,'{"entries":[{"modified":true}]}');assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha:toolSha,readOnlyGit:git,extraPaths:[registry]}),false);git(['add',registry]);git(['commit','-m','changed critical policy']);assert.equal(recoveryCodeUnchangedAt({toolSha,mainSha:git(['rev-parse','HEAD']).trim(),readOnlyGit:git,extraPaths:[registry]}),false)}finally{rmSync(dir,{recursive:true,force:true})}
});
