-- Issue #3737. Version reserved by migration-author claim #4044.
-- derived-from: none
-- Close two Tracking production-cutover gaps in dflow_prod found by the #2873
-- four-service inventory. Production designflow-tracking runs single-schema, so
-- it resolves every model (including product_type_factory_time, mapped to plm
-- only in multi-schema mode) inside dflow_prod.
--
--   1. Shipment-notice outbox: canonical migration 20260909084253, re-targeted
--      from dflow to dflow_prod and nothing else.
--   2. Factory-time templates: canonical migration 20260911214438, re-targeted
--      from plm to dflow_prod and nothing else.
--
-- Boundaries:
--   * No application rows are copied or created.
--   * No object references dflow or plm; nothing is granted to PUBLIC, anon,
--     authenticated or service_role. Runtime grants are #2873. The canonical
--     conditional grant to the legacy `designflow` role is not replayed
--     (dflow_prod stays closed until #2873).
--   * SECURITY DEFINER pins search_path to dflow_prod, pg_catalog (canonical
--     order, schema re-targeted).
--   * Fails closed if a target object already exists, a dependency is missing,
--     or dflow_prod."FactoryTime" holds rows (names cannot be invented).
-- Depends on #2875 (dflow_prod.sample_shipment).

begin;

do $pre$
begin
  if to_regclass('dflow_prod.sample_shipment') is null then raise exception '#3737: dflow_prod.sample_shipment is missing (#2875 must land first)'; end if;
  if to_regclass('dflow_prod.users') is null then raise exception '#3737: dflow_prod.users is missing'; end if;
  if to_regclass('dflow_prod."FactoryTime"') is null then raise exception '#3737: dflow_prod."FactoryTime" is missing'; end if;
  if to_regclass('dflow_prod.sample_shipment_notice') is not null
     or to_regclass('dflow_prod.sample_shipment_notice_recipient') is not null
     or to_regclass('dflow_prod.product_type_factory_time') is not null
     or to_regclass('dflow_prod.factory_time_name_ci_key') is not null
     or to_regprocedure('dflow_prod.claim_sample_shipment_notice(bigint)') is not null
     or to_regprocedure('dflow_prod.prevent_sample_shipment_notice_snapshot_mutation()') is not null
     or to_regprocedure('dflow_prod.prevent_sample_shipment_notice_recipient_snapshot_mutation()') is not null
  then raise exception '#3737: a target object already exists in dflow_prod'; end if;
  if exists (select 1 from information_schema.columns where table_schema='dflow_prod' and table_name='FactoryTime' and column_name in ('name','description','tags','updated_by'))
  then raise exception '#3737: dflow_prod."FactoryTime" already has template columns'; end if;
end $pre$;

-- 1. Shipment-notice outbox (canonical 20260909084253).
CREATE TABLE dflow_prod.sample_shipment_notice (
  sample_shipment_notice_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_shipment_id_fk bigint NOT NULL REFERENCES dflow_prod.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','sending','sent','failed')),
  subject text NOT NULL CHECK (btrim(subject) <> ''),
  body_html text NOT NULL,
  body_text text,
  provider_idempotency_key uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0 AND attempt_count <= 5),
  last_attempt_at timestamptz,
  next_attempt_at timestamptz,
  sent_at timestamptz,
  provider_message_id text,
  last_error text,
  created_by_user_id integer NOT NULL REFERENCES dflow_prod.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_shipment_notice_shipment_uniq UNIQUE (sample_shipment_id_fk),
  CONSTRAINT sample_shipment_notice_key_uniq UNIQUE (provider_idempotency_key),
  CONSTRAINT sample_shipment_notice_state_dates_ck CHECK (
    (state = 'sent') = (sent_at IS NOT NULL)
  )
);

CREATE TABLE dflow_prod.sample_shipment_notice_recipient (
  sample_shipment_notice_recipient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_shipment_notice_id_fk bigint NOT NULL REFERENCES dflow_prod.sample_shipment_notice(sample_shipment_notice_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user_id_fk integer NOT NULL REFERENCES dflow_prod.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  recipient_function text NOT NULL CHECK (recipient_function IN ('sales','design','both')),
  recipient_name_snapshot text NOT NULL CHECK (btrim(recipient_name_snapshot) <> ''),
  recipient_email_snapshot text NOT NULL CHECK (btrim(recipient_email_snapshot) <> ''),
  CONSTRAINT sample_shipment_notice_recipient_uniq UNIQUE (sample_shipment_notice_id_fk, user_id_fk)
);

CREATE OR REPLACE FUNCTION dflow_prod.prevent_sample_shipment_notice_snapshot_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sample_shipment_id_fk IS DISTINCT FROM OLD.sample_shipment_id_fk
     OR NEW.subject IS DISTINCT FROM OLD.subject OR NEW.body_html IS DISTINCT FROM OLD.body_html
     OR NEW.body_text IS DISTINCT FROM OLD.body_text OR NEW.provider_idempotency_key IS DISTINCT FROM OLD.provider_idempotency_key
     OR NEW.created_by_user_id IS DISTINCT FROM OLD.created_by_user_id OR NEW.created_by_user IS DISTINCT FROM OLD.created_by_user
  THEN RAISE EXCEPTION 'Sample shipment notice snapshots are immutable'; END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION dflow_prod.prevent_sample_shipment_notice_recipient_snapshot_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sample_shipment_notice_id_fk IS DISTINCT FROM OLD.sample_shipment_notice_id_fk
     OR NEW.user_id_fk IS DISTINCT FROM OLD.user_id_fk OR NEW.recipient_function IS DISTINCT FROM OLD.recipient_function
     OR NEW.recipient_name_snapshot IS DISTINCT FROM OLD.recipient_name_snapshot
     OR NEW.recipient_email_snapshot IS DISTINCT FROM OLD.recipient_email_snapshot
  THEN RAISE EXCEPTION 'Sample shipment notice recipient snapshots are immutable'; END IF;
  RETURN NEW;
END; $$;

CREATE TRIGGER sample_shipment_notice_snapshot_immutable BEFORE UPDATE ON dflow_prod.sample_shipment_notice
FOR EACH ROW EXECUTE FUNCTION dflow_prod.prevent_sample_shipment_notice_snapshot_mutation();
CREATE TRIGGER sample_shipment_notice_recipient_snapshot_immutable BEFORE UPDATE ON dflow_prod.sample_shipment_notice_recipient
FOR EACH ROW EXECUTE FUNCTION dflow_prod.prevent_sample_shipment_notice_recipient_snapshot_mutation();
CREATE OR REPLACE FUNCTION dflow_prod.claim_sample_shipment_notice(p_notice_id bigint)
RETURNS TABLE (notice_id bigint, subject text, body_html text, provider_idempotency_key uuid, recipient_emails text[])
LANGUAGE plpgsql SECURITY DEFINER SET search_path = dflow_prod, pg_catalog AS $$
DECLARE v_notice dflow_prod.sample_shipment_notice;
BEGIN
  SELECT * INTO v_notice FROM dflow_prod.sample_shipment_notice
  WHERE sample_shipment_notice_id = p_notice_id
    AND attempt_count < 5
    AND (state IN ('pending','failed') AND (next_attempt_at IS NULL OR next_attempt_at <= now())
         OR state = 'sending' AND last_attempt_at <= now() - interval '5 minutes')
  FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE dflow_prod.sample_shipment_notice n
  SET state='sending', attempt_count=n.attempt_count+1, last_attempt_at=now(), next_attempt_at=NULL,
      last_error=NULL, updated_at=now()
  WHERE n.sample_shipment_notice_id = v_notice.sample_shipment_notice_id;
  RETURN QUERY SELECT v_notice.sample_shipment_notice_id, v_notice.subject, v_notice.body_html,
    v_notice.provider_idempotency_key,
    COALESCE((SELECT array_agg(r.recipient_email_snapshot ORDER BY r.sample_shipment_notice_recipient_id)
              FROM dflow_prod.sample_shipment_notice_recipient r
              WHERE r.sample_shipment_notice_id_fk=v_notice.sample_shipment_notice_id), ARRAY[]::text[]);
END; $$;


REVOKE ALL ON dflow_prod.sample_shipment_notice, dflow_prod.sample_shipment_notice_recipient FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION dflow_prod.claim_sample_shipment_notice(bigint) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION dflow_prod.prevent_sample_shipment_notice_snapshot_mutation() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION dflow_prod.prevent_sample_shipment_notice_recipient_snapshot_mutation() FROM PUBLIC, anon, authenticated, service_role;

COMMENT ON TABLE dflow_prod.sample_shipment_notice IS 'Immutable shipment email snapshot with bounded, provider-idempotent delivery state.';
COMMENT ON FUNCTION dflow_prod.claim_sample_shipment_notice(bigint) IS 'Atomically claims one pending, failed, or stale sending notice for server-side delivery; max five attempts and five-minute spacing.';

-- 2. Factory-time templates (canonical 20260911214438).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM dflow_prod."FactoryTime") THEN
    RAISE EXCEPTION 'dflow_prod."FactoryTime" already holds rows; template names cannot be invented by a migration (#2724, #3737)';
  END IF;
END $$;

ALTER TABLE dflow_prod."FactoryTime"
  ADD COLUMN name text,
  ADD COLUMN description text,
  ADD COLUMN tags text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN updated_by text;

ALTER TABLE dflow_prod."FactoryTime"
  ALTER COLUMN name SET NOT NULL,
  ALTER COLUMN product_subtype DROP NOT NULL,
  ALTER COLUMN resampling_days DROP DEFAULT;

ALTER TABLE dflow_prod."FactoryTime"
  ADD CONSTRAINT "FactoryTime_name_not_blank_check"
    CHECK (btrim(name) <> ''),
  ADD CONSTRAINT "FactoryTime_tags_no_null_check"
    CHECK (array_position(tags, NULL) IS NULL),
  ADD CONSTRAINT "FactoryTime_days_nonnegative_check"
    CHECK (
      (sampling_days IS NULL OR sampling_days >= 0)
      AND (resampling_days IS NULL OR resampling_days >= 0)
      AND (mass_production_days IS NULL OR mass_production_days >= 0)
    );

CREATE UNIQUE INDEX factory_time_name_ci_key
  ON dflow_prod."FactoryTime" (lower(btrim(name)));

COMMENT ON COLUMN dflow_prod."FactoryTime".name IS
  'Template name shown in DesignFlow; unique ignoring case and surrounding spaces (#2724).';
COMMENT ON COLUMN dflow_prod."FactoryTime".description IS 'Optional template description (#2724).';
COMMENT ON COLUMN dflow_prod."FactoryTime".tags IS 'Free-text template tags; empty array when untagged (#2724).';
COMMENT ON COLUMN dflow_prod."FactoryTime".updated_by IS 'App user (email or id) who last edited the template (#2724).';
COMMENT ON COLUMN dflow_prod."FactoryTime".product_subtype IS
  'Informational only since #2724; nothing matches templates on it. Product types are assigned in dflow_prod.product_type_factory_time.';

CREATE TABLE dflow_prod.product_type_factory_time (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mg_category text NOT NULL,
  mg01_code text NOT NULL,
  mg02_code text NOT NULL,
  factory_time_id integer NOT NULL
    REFERENCES dflow_prod."FactoryTime"(id) ON DELETE RESTRICT,
  assigned_by text NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  previous_factory_time_id integer,
  CONSTRAINT product_type_factory_time_product_type_key
    UNIQUE (mg_category, mg01_code, mg02_code),
  CONSTRAINT product_type_factory_time_key_trimmed_check
    CHECK (
      mg_category <> '' AND mg_category = btrim(mg_category)
      AND mg01_code <> '' AND mg01_code = btrim(mg01_code)
      AND mg02_code <> '' AND mg02_code = btrim(mg02_code)
    ),
  CONSTRAINT product_type_factory_time_assigned_by_not_blank_check
    CHECK (btrim(assigned_by) <> '')
);

CREATE INDEX product_type_factory_time_factory_time_id_idx
  ON dflow_prod.product_type_factory_time (factory_time_id);

COMMENT ON TABLE dflow_prod.product_type_factory_time IS
  'One lead-time template per DesignFlow product type (mgCategory, MG01, MG02), assigned by hand; many product types may share a template. Deleting an in-use template is refused (#2724).';
COMMENT ON COLUMN dflow_prod.product_type_factory_time.previous_factory_time_id IS
  'Template this assignment replaced at its latest reassignment; not a foreign key so retired templates can still be deleted.';

-- Canonical plm enables RLS because the plm API connects as the table owner.
-- dflow_prod has no RLS on any table; access is by explicit least-privilege
-- grants (#2873), and an RLS-enabled table with no policy would deny the
-- Tracking runtime role every row. RLS is therefore deliberately not enabled.
REVOKE ALL ON TABLE dflow_prod.product_type_factory_time FROM PUBLIC, anon, authenticated, service_role;

-- Post-verify: nothing references dflow or plm, and no client role holds access.
do $post$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
             where n.nspname='dflow_prod' and p.proname in ('claim_sample_shipment_notice','prevent_sample_shipment_notice_snapshot_mutation','prevent_sample_shipment_notice_recipient_snapshot_mutation')
               and (pg_get_functiondef(p.oid) ~ '\mdflow\.' or pg_get_functiondef(p.oid) ~ '\mplm\.'))
  then raise exception '#3737 VERIFY FAILED: a function references dflow or plm'; end if;
  if exists (select 1 from information_schema.role_table_grants
             where table_schema='dflow_prod' and table_name in ('sample_shipment_notice','sample_shipment_notice_recipient','product_type_factory_time')
               and grantee in ('PUBLIC','anon','authenticated','service_role'))
  then raise exception '#3737 VERIFY FAILED: a client role holds table access'; end if;
  if has_function_privilege('anon','dflow_prod.claim_sample_shipment_notice(bigint)','EXECUTE')
     or has_function_privilege('authenticated','dflow_prod.claim_sample_shipment_notice(bigint)','EXECUTE')
     or has_function_privilege('service_role','dflow_prod.claim_sample_shipment_notice(bigint)','EXECUTE')
  then raise exception '#3737 VERIFY FAILED: a client role can execute claim_sample_shipment_notice'; end if;
  if exists (select 1 from pg_roles r cross join pg_class c join pg_namespace n on n.oid=c.relnamespace
             where r.rolname in ('anon','authenticated','service_role') and n.nspname='dflow_prod'
               and c.relname in ('sample_shipment_notice','sample_shipment_notice_recipient','product_type_factory_time')
               and has_table_privilege(r.rolname,c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'))
  then raise exception '#3737 VERIFY FAILED: a client role holds effective table access'; end if;
  if exists (select 1 from pg_roles r cross join pg_proc p join pg_namespace n on n.oid=p.pronamespace
             where r.rolname in ('anon','authenticated','service_role') and n.nspname='dflow_prod'
               and p.proname in ('claim_sample_shipment_notice','prevent_sample_shipment_notice_snapshot_mutation','prevent_sample_shipment_notice_recipient_snapshot_mutation')
               and has_function_privilege(r.rolname,p.oid,'EXECUTE'))
  then raise exception '#3737 VERIFY FAILED: a client role holds effective function access'; end if;
  if exists (select 1 from pg_depend d join pg_class c on c.oid=d.objid cross join pg_roles r
             where d.refobjid in (to_regclass('dflow_prod.sample_shipment_notice'),to_regclass('dflow_prod.sample_shipment_notice_recipient'),to_regclass('dflow_prod.product_type_factory_time'))
               and c.relkind='S' and r.rolname in ('anon','authenticated','service_role')
               and has_sequence_privilege(r.rolname,c.oid,'USAGE,SELECT,UPDATE'))
  then raise exception '#3737 VERIFY FAILED: a client role holds effective sequence access'; end if;
end $post$;

commit;
